[package]
name = "prime"
version = "0.1.0"
authors = ["Omid Rad"]
edition = "2018"

[dependencies]
primal = "0.2"
tokio = { version = "0.2", features = ["full"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"